import {test} from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {template,checkGraph,buildStack,importStack,canonical,digest,connectionProblem,suggestAdapter,type ComposeGraph} from "../apps/neurolab-web/lib/composeCompiler.ts";
import {loadCompiledStack,replayStack,scenarioInput,type ReplayBundle} from "../apps/neurolab-web/lib/composeRuntime.ts";
const load=async(k:string)=>readFileSync("blocks/"+k+"/1.0.0/block.json","utf8");
test("three runnable templates compile; BioPilot identifies unresolved ABIs",async()=>{for(const t of ["shield","brake","arbiter"]){const p=await buildStack(template(t),load);assert.equal(p.manifest.executable,true);assert.equal(checkGraph(p.graph).errors.length,0);}const p=await buildStack(template("biopilot"),load);assert.equal(p.manifest.executable,false);assert.equal(checkGraph(p.graph).blocked.length,3);await assert.rejects(()=>loadCompiledStack(p),/source-only/);});
test("canonical build binds behavior and ignores graph ordering",async()=>{const g=template(),a=await buildStack(g,load),b=await buildStack({...g,nodes:[...g.nodes].reverse(),edges:[...g.edges].reverse()},load);assert.equal(canonical(a),canonical(b));assert.deepEqual(await importStack(canonical(a)),a);for(const change of [{policy:"FAST" as const},{deadlineMs:12},{nodes:g.nodes.map(n=>n.type==="SafetyGate"?{...n,params:{threshold:20000}}:n)}])assert.notEqual((await buildStack({...g,...change},load)).manifest.stackId,a.manifest.stackId);});
test("strict import preserves valid packages compiled before verifier metadata",async()=>{const current=await buildStack(template(),load),legacy=structuredClone(current);legacy.verification={policy:legacy.graph.policy,scope:"local-unsigned-replay"};legacy.manifest.stackId=await digest(canonical({runtime:legacy.manifest.runtime,graph:{nodes:legacy.graph.nodes,edges:legacy.graph.edges,deadlineMs:legacy.graph.deadlineMs,policy:legacy.graph.policy},lockfile:legacy.lockfile,runtimePlan:legacy.runtimePlan,verification:legacy.verification}));assert.deepEqual(await importStack(canonical(legacy)),legacy);});
test("tampering with model bytes or runtime plan fails import",async()=>{const p=await buildStack(template(),load);const a=structuredClone(p);a.modules.loomguard+=" ";await assert.rejects(()=>importStack(canonical(a)),/mismatch/);const b=structuredClone(p);b.runtimePlan.periods.LoomGuard=10;await assert.rejects(()=>importStack(canonical(b)),/mismatch/);});
test("malformed graphs, missing inputs, mismatches and duplicate writers fail",()=>{for(const bad of [null,{}, {nodes:[null],edges:[]}])assert.ok(checkGraph(bad).errors.length);const g=template();assert.ok(checkGraph({...g,edges:g.edges.slice(1)}).errors.some(e=>e.code==="MISSING_INPUT"));assert.ok(connectionProblem(g,"WorldState.world","LoomGuard.event_vision"));assert.deepEqual(suggestAdapter(g,"WorldState.world","LoomGuard.event_vision"),["WorldToEvents"]);assert.ok(connectionProblem(g,g.edges[0].from,g.edges[0].to));assert.ok(checkGraph({...g,nodes:g.nodes.map(n=>n.type==="WorldState"?{...n,params:{hz:30}}:n)}).errors.some(e=>e.code==="PARAMETER"));assert.ok(checkGraph({...g,deadlineMs:1}).errors.some(e=>e.code==="DEADLINE"));});
test("multiple instances compile and implicit feedback is rejected",async()=>{const g=template();g.nodes.push({id:"gate2",type:"SafetyGate"});g.edges.push({from:"LoomGuard.avoidance_vector",to:"gate2.safety"});assert.equal((await buildStack(g,load)).manifest.executable,true);const cycle:ComposeGraph={name:"Cycle",version:"1.0.0",policy:"AUDIT",deadlineMs:10,nodes:[{id:"a",type:"Clamp"},{id:"b",type:"Clamp"},{id:"out",type:"DroneControl"}],edges:[{from:"a.command",to:"b.control"},{from:"b.command",to:"a.control"},{from:"a.command",to:"out.control"}]};assert.ok(checkGraph(cycle).errors.some(e=>e.code==="CYCLE"));});
test("explicit state breaks cycles and starts from STOP",async()=>{const g:ComposeGraph={name:"Delay",version:"1.0.0",policy:"AUDIT",deadlineMs:10,nodes:[{id:"memory",type:"PreviousValue"},{id:"clamp",type:"Clamp"},{id:"out",type:"DroneControl"}],edges:[{from:"memory.previous",to:"clamp.control"},{from:"clamp.command",to:"memory.control"},{from:"clamp.command",to:"out.control"}]};const p=await buildStack(g,load),vm=await loadCompiledStack(p);assert.deepEqual((await vm.step({})).actions.out.values,[0,0,0]);});
test("actual LoomGuard output reaches safety gate and actuator",async()=>{const p=await buildStack(template(),load),vm=await loadCompiledStack(p);const clear=await vm.step(scenarioInput(p,false));assert.deepEqual(clear.actions.DroneControl.values,[0,32768,0]);let stop=false;for(let i=0;i<30;i++){const r=await vm.step(scenarioInput(p,true));if(r.actions.DroneControl.values[2]){stop=true;assert.equal(r.actions.DroneControl.values[1],0);assert.ok(r.events.some(e=>e.type==="TRIGGER"));assert.ok(r.events.some(e=>e.type==="SAFETY_OVERRIDE"));break;}}assert.ok(stop);});
test("arbiter preempts nominal steering and receipt replays in fresh runtime",async()=>{const p=await buildStack(template("arbiter"),load),vm=await loadCompiledStack(p);const first=await vm.step(scenarioInput(p,false));assert.equal(first.actions.RoverSteering.values[0],19661);let bundle:ReplayBundle|undefined;for(let i=0;i<30;i++){const r=await vm.step(scenarioInput(p,true));if(r.replay){bundle=r.replay;break;}}assert.ok(bundle);assert.equal((await replayStack(p,bundle)).matched,true);assert.equal(bundle.receipt.stackId,p.manifest.stackId);assert.ok(bundle.receipt.events.some(e=>e.node==="Arbiter"&&e.type==="SAFETY_OVERRIDE"));const altered=structuredClone(bundle);altered.receipt.actions.RoverSteering.values[0]++;await assert.rejects(()=>replayStack(p,altered),/mismatch/);const input=structuredClone(bundle);input.input.WorldState.values[0]=0;await assert.rejects(()=>replayStack(p,input),/mismatch/);});
test("braking reuses exact neural identity across embodiments",async()=>{const shield=await buildStack(template(),load),brake=await buildStack(template("brake"),load);assert.equal(shield.lockfile.loomguard.digest,brake.lockfile.loomguard.digest);assert.notEqual(shield.manifest.stackId,brake.manifest.stackId);const vm=await loadCompiledStack(brake);let result;for(let i=0;i<10;i++)result=await vm.step(scenarioInput(brake,true));assert.equal(result!.actions.CarBrake.values[0],65536);});
test("multi-rate schedule executes only due nodes and retains latest values",async()=>{const g=template();g.nodes=g.nodes.map(n=>n.type==="DroneControl"?{...n,params:{hz:100}}:n);const p=await buildStack(g,load),vm=await loadCompiledStack(p);for(let i=0;i<12;i++){const r=await vm.step(scenarioInput(p,false));assert.equal(r.events.some(e=>e.node==="DroneControl"),i%10===0);assert.equal(r.events.some(e=>e.node==="LoomGuard"),i%5===0);}});
test("failed input and invalid snapshots leave state unchanged",async()=>{const p=await buildStack(template(),load),vm=await loadCompiledStack(p),before=vm.snapshot();await assert.rejects(()=>vm.step({}));assert.deepEqual(vm.snapshot(),before);const bad=structuredClone(before);bad.neurons.LoomGuard[16]=3;assert.throws(()=>vm.restore(bad));assert.deepEqual(vm.snapshot(),before);const badInput=scenarioInput(p,false);badInput.WorldState.values[0]=NaN;await assert.rejects(()=>vm.step(badInput));assert.deepEqual(vm.snapshot(),before);});
test("FAST suppresses receipts, DEBUG chains them and restores deterministically",async()=>{for(const policy of ["FAST","DEBUG"] as const){const p=await buildStack({...template(),policy},load),vm=await loadCompiledStack(p);const first=await vm.step(scenarioInput(p,true));assert.equal(!!first.receipt,policy==="DEBUG");if(first.replay)assert.equal((await replayStack(p,first.replay)).matched,true);const state=vm.snapshot(),fresh=await loadCompiledStack(p);fresh.restore(state);for(let i=0;i<5;i++){const a=await vm.step(scenarioInput(p,true)),b=await fresh.step(scenarioInput(p,true));assert.equal(canonical(a),canonical(b));if(a.receipt)assert.equal(a.receipt.previousReceiptHash,first.receipt!.hash);}}});
test("pinned local bytes remain portable",async()=>{const g=template(),raw=await load("loomguard"),hash=await digest(raw);g.nodes=g.nodes.map(n=>n.type==="LoomGuard"?{...n,module:{id:"local-lab/reflex",version:"0.1.0",digest:hash}}:n);const p=await buildStack(g,async()=>raw);assert.equal(p.modules["local-lab/reflex@0.1.0"],raw);assert.equal(canonical(await importStack(canonical(p))),canonical(p));g.nodes.find(n=>n.type==="LoomGuard")!.module!.digest="sha256:"+"0".repeat(64);await assert.rejects(()=>buildStack(g,async()=>raw),/mismatch/);});

test("slow sensors cannot hide behind a fast adapter",()=>{const g=template();g.nodes=g.nodes.map(n=>n.type==="WorldState"?{...n,params:{hz:25}}:n);assert.ok(checkGraph(g).errors.some(e=>e.code==="RATE"));});
test("exported standalone runtime reproduces the exact package",async()=>{const {loadCompiledStack:standalone}=await import("../apps/neurolab-web/public/runtime/compose-runtime.mjs");const p=await buildStack(template("arbiter"),load),browser=await loadCompiledStack(p),portable=await standalone(canonical(p));for(let i=0;i<12;i++)assert.equal(canonical(await browser.step(scenarioInput(p,i>3))),canonical(await portable.step(scenarioInput(p,i>3))));});
test("Verify checks the full Stack decision and rejects a changed actuator command",async()=>{const {verifyStackEvidence}=await import("../apps/neurolab-web/lib/verification.ts");const p=await buildStack(template("arbiter"),load),vm=await loadCompiledStack(p);const r=await vm.step(scenarioInput(p,true));assert.ok(r.replay);assert.equal((await verifyStackEvidence(canonical(p),r.replay)).outcome,"MATCH");r.replay.receipt.actions.RoverSteering.values[1]=1;assert.equal((await verifyStackEvidence(canonical(p),r.replay)).outcome,"MISMATCH");});
test("local publication keeps executable Stack identity and exact bytes",async()=>{const {preparePublication}=await import("../apps/neurolab-web/lib/libraryServer.ts");const p=await buildStack(template(),load),raw=canonical(p);const r=await preparePublication({owner:"test-lab",name:"compose-shield",version:"0.1.0",kind:"NeuroStack",description:"A composed collision reflex for local testing.",task:"Collision avoidance",license:"Not specified",readme:"This is a local compositional execution test.",provenance:"Built from the bundled LoomGuard model.",artifact:raw,testVectors:"[]"});assert.equal(r.files["stack.synapse"].toString(),raw);assert.equal(r.item.modelDigest,p.manifest.stackId);assert.equal(r.item.runtime,"Compose JS · executable");assert.deepEqual(r.item.inputs,["WorldState.world"]);assert.equal(r.item.testsRun,false);});

test("step owns its input and prevents mid-step snapshots",async()=>{const p=await buildStack(template(),load),vm=await loadCompiledStack(p),input=scenarioInput(p,true),pending=vm.step(input);input.WorldState.values[0]=0;assert.throws(()=>vm.snapshot(),/stepping/);const r=await pending;assert.ok(r.replay);assert.equal(r.replay.input.WorldState.values[0],52429);assert.equal(r.receipt!.packageHash,await digest(canonical(p)));assert.equal((await replayStack(p,r.replay)).matched,true);});
