import {test} from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {captureEvidence,verifyBrowserEvidence,verifyArtifact,signedReplayReport} from "../apps/neurolab-web/lib/verification.ts";
import {SynapseVmJs,q16} from "../apps/neurolab-web/lib/synapseVm.ts";
import {digest} from "../apps/neurolab-web/lib/stackCompiler.ts";
const model=readFileSync("blocks/loomguard/1.0.0/block.json","utf8");
async function evidence(){const vm=new SynapseVmJs(JSON.parse(model));vm.step([0,0,0,0],0);const before=Array.from(vm.snapshot()),input=[q16(.8),0,0,q16(.6)],out=vm.step(input,1);return captureEvidence(model,1,input,before,out,Array.from(vm.snapshot()));}
test("exact replay matches complete neural output and post-state without trust overclaim",async()=>{const e=await evidence(),r=await verifyBrowserEvidence(e);assert.equal(r.outcome,"MATCH");assert.equal(r.claims.find(c=>c.id==="output")!.status,"match");assert.equal(r.claims.find(c=>c.id==="after")!.status,"match");assert.equal(r.claims.find(c=>c.id==="anchor")!.status,"missing");for(const key of ["signature","device","external","control"])assert.equal(r.claims.find(c=>c.id===key),undefined);});
test("modified model, input, pre-state, output and post-state cannot pass",async()=>{for(const field of ["model","input","stateBefore","output","stateAfter"]){const e=await evidence();if(field==="model")e.model+=" ";else if(field==="input")e.input[0]--;else if(field==="stateBefore")e.stateBefore[12]++;else if(field==="output")e.output.danger++;else e.commitments.stateAfter="sha256:"+"0".repeat(64);assert.equal((await verifyBrowserEvidence(e)).outcome,"MISMATCH",field);}});
test("even a rehashed false output must equal actual replay",async()=>{const e=await evidence();e.output.trigger=!e.output.trigger;const canonical=(await import("../apps/neurolab-web/lib/stackCompiler.ts")).canonical;e.commitments.output=await digest(canonical(e.output));assert.equal((await verifyBrowserEvidence(e)).outcome,"MISMATCH");});
test("unknown runtime, missing state and invalid bytes fail closed",async()=>{const e=await evidence();await assert.rejects(()=>verifyBrowserEvidence({...e,runtime:"unknown"}));await assert.rejects(()=>verifyBrowserEvidence({...e,stateBefore:[]}));const bad=structuredClone(e);bad.stateBefore[0]=256;await assert.rejects(()=>verifyBrowserEvidence(bad));});
test("artifact hash is computed until an expected digest is supplied",async()=>{assert.equal((await verifyArtifact(model)).outcome,"INCOMPLETE");assert.equal((await verifyArtifact(model,await digest(model))).outcome,"MATCH");assert.equal((await verifyArtifact(model,"sha256:"+"0".repeat(64))).outcome,"MISMATCH");await assert.rejects(()=>verifyArtifact(model,"bad"));});
test("validator aggregate success cannot hide missing or failed checks",()=>{assert.equal(signedReplayReport({valid:true},{}).outcome,"INCOMPLETE");const keys=["receiptIdMatch","signatureValid","blockRootMatch","runtimeMatch","inputMatch","stateBeforeMatch","actionMatch","traceRootMatch","stateAfterMatch"];const response={valid:true,...Object.fromEntries(keys.map(k=>[k,true]))};assert.equal(signedReplayReport(response,{}).outcome,"MATCH");assert.equal(signedReplayReport({...response,actionMatch:false},{}).outcome,"MISMATCH");assert.equal(signedReplayReport({...response,signatureValid:"true"},{}).outcome,"INCOMPLETE");});
