"use client";
import Link from "next/link";
import dynamic from "next/dynamic";
import {useEffect,useMemo,useRef,useState,type PointerEvent} from "react";
import {DEFINITIONS,RATES,template,paramsFor,checkGraph,connectionProblem,suggestAdapter,buildStack,importStack,canonical,digest,moduleKey,type ComposeGraph,type ComposeNode,type ComposePackage} from "@/lib/composeCompiler";
import {loadCompiledStack,replayStack,scenarioInput,type CompiledStack,type RuntimeEvent,type ReplayBundle,type Inputs} from "@/lib/composeRuntime";
import type {LibraryItem} from "@/lib/library";
import {ComposeAssistant} from "./ComposeAssistant";
import {DRAFT_KEY,BUILD_KEY,draftFingerprint,restoreBuild,canComposeBlock} from "@/lib/workflow";
const World=dynamic(()=>import("./ComposeWorld").then(m=>m.ComposeWorld),{ssr:false,loading:()=> <p>Loading command preview…</p>});
type Position={x:number;y:number};
type Draft={graph:ComposeGraph;positions:Record<string,Position>;modules:Record<string,string>};
const KEY=DRAFT_KEY,families=["sensor","adapter","neuroblock","control","state","actuator"];
const short=(s:string)=>s.length>20?s.slice(0,13)+"…"+s.slice(-5):s;
function layout(g:ComposeGraph):Record<string,Position>{
 const levels=new Map<string,number>();const ordered=checkGraph(g).order;for(const id of [...ordered,...g.nodes.map(n=>n.id).filter(id=>!ordered.includes(id))]){const n=g.nodes.find(n=>n.id===id)!;const parents=n.type==="PreviousValue"?[]:g.edges.filter(e=>e.to.startsWith(id+".")).map(e=>e.from.split(".")[0]);levels.set(id,Math.max(0,...parents.map(id=>(levels.get(id)??-1)+1)));}
 const count:Record<number,number>={};return Object.fromEntries(g.nodes.map(n=>{const level=levels.get(n.id)??0,row=count[level]??0;count[level]=row+1;return [n.id,{x:40+level*285,y:50+row*250}];}));
}
function checkedDraft(value:unknown):Draft {
 const v=value as Draft;const c=checkGraph(v?.graph);if(c.errors.some(e=>["GRAPH","NODE","LIMIT","PARAMETER","MODULE","EDGE"].includes(e.code))||typeof v.graph.name!=="string"||typeof v.graph.version!=="string")throw Error("Unsupported draft structure.");
 const fallback=layout(v.graph),positions=Object.fromEntries(v.graph.nodes.map(n=>{const p=v.positions?.[n.id];return [n.id,p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&Math.abs(p.x)<100000&&Math.abs(p.y)<100000?p:fallback[n.id]];}));
 if(!v.modules||typeof v.modules!=="object"||Array.isArray(v.modules)||Object.values(v.modules).some(raw=>typeof raw!=="string"||raw.length>4000000))throw Error("Invalid draft modules.");
 return {graph:v.graph,positions,modules:v.modules};
}
function initial():Draft{const graph=template();return {graph,positions:layout(graph),modules:{}};}
function download(name:string,raw:string,mime="application/json"){const url=URL.createObjectURL(new Blob([raw],{type:mime}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ComposeStudio({mode="compose"}:{mode?:"compose"|"compile"|"simulate"}){
 const [release,setRelease]=useState<{item:LibraryItem;raw:string}|null>(null);
 const [draft,setDraft]=useState<Draft>(initial),[ready,setReady]=useState(false),[status,setStatus]=useState(""),[error,setError]=useState(""),[selected,setSelected]=useState("LoomGuard"),[edgeIndex,setEdgeIndex]=useState<number|null>(null),[pending,setPending]=useState(""),[search,setSearch]=useState(""),[tab,setTab]=useState<"inspect"|"build"|"run">("inspect");
 const [adapterOffer,setAdapterOffer]=useState<{from:string;to:string;types:string[]}|null>(null);
 const [past,setPast]=useState<Draft[]>([]),[future,setFuture]=useState<Draft[]>([]),[pan,setPan]=useState({x:0,y:0}),[zoom,setZoom]=useState(.7),[busy,setBusy]=useState(false),[built,setBuilt]=useState<{pkg:ComposePackage;fingerprint:string;hash:string}|null>(null),[library,setLibrary]=useState<LibraryItem[]>([]);
 const [running,setRunning]=useState(false),[obstacle,setObstacle]=useState(false),[actions,setActions]=useState<Inputs>({}),[events,setEvents]=useState<RuntimeEvent[]>([]),[event,setEvent]=useState<RuntimeEvent|null>(null),[replay,setReplay]=useState<ReplayBundle|null>(null),[replayResult,setReplayResult]=useState(""),[tick,setTick]=useState(0);
 const stage=useRef<HTMLDivElement>(null),drag=useRef<{id:string;px:number;py:number;x:number;y:number;original:Draft}|null>(null),panDrag=useRef<{px:number;py:number;x:number;y:number}|null>(null),runtime=useRef<CompiledStack|null>(null),stepping=useRef(false),generation=useRef(0);
 const {graph,positions,modules}=draft;const draftRef=useRef(draft);draftRef.current=draft;const fingerprint=draftFingerprint(draft),fingerRef=useRef(fingerprint);fingerRef.current=fingerprint;
 const active=built?.fingerprint===fingerprint?built:null;
 const validation=useMemo(()=>checkGraph(graph),[graph]),node=graph.nodes.find(n=>n.id===selected),nodeDef=node?DEFINITIONS[node.type]:null;
 const edge=edgeIndex===null?null:graph.edges[edgeIndex];
 function persistDraft(next:Draft){try{localStorage.setItem(KEY,JSON.stringify(next));}catch{setStatus("Browser storage full. Download your draft to keep it.");}}
 function commit(next:Draft){setPast(p=>[...p.slice(-29),draftRef.current]);setFuture([]);setDraft(next);persistDraft(next);setError("");setPending("");setAdapterOffer(null);}
 function updateGraph(g:ComposeGraph){commit({...draftRef.current,graph:g});}
 // A synthesised graph replaces the draft wholesale; it arrives already checked by checkGraph.
 function applyPlan(g:ComposeGraph){const positions=layout(g);commit({...draftRef.current,graph:g,positions});setSelected(g.nodes[0]?.id??"");setEdgeIndex(null);setTab("inspect");setStatus("Placed a synthesised graph. Review it before compiling.");fit(positions);}
 function undo(){if(!past.length)return;setFuture(f=>[draftRef.current,...f]);setDraft(past[past.length-1]);persistDraft(past[past.length-1]);setPast(p=>p.slice(0,-1));setPending("");}
 function redo(){if(!future.length)return;setPast(p=>[...p,draftRef.current]);setDraft(future[0]);persistDraft(future[0]);setFuture(f=>f.slice(1));setPending("");}
 function fit(pos=positions){const box=stage.current;if(!box||!Object.keys(pos).length)return;const ps=Object.values(pos),minX=Math.min(...ps.map(p=>p.x)),minY=Math.min(...ps.map(p=>p.y)),w=Math.max(...ps.map(p=>p.x+235))-minX,h=Math.max(...ps.map(p=>p.y+220))-minY;const z=Math.min(1,Math.max(.2,Math.min((box.clientWidth-60)/w,(box.clientHeight-60)/h)));setZoom(z);setPan({x:(box.clientWidth-w*z)/2-minX*z,y:(box.clientHeight-h*z)/2-minY*z});}
 useEffect(()=>{let cancelled=false;void(async()=>{try{const raw=localStorage.getItem(KEY),saved=raw?checkedDraft(JSON.parse(raw)):initial();setDraft(saved);setStatus(raw?"Restored local draft":"Collision Shield starter graph");const stored=localStorage.getItem(BUILD_KEY);if(stored){try{const build=await restoreBuild(stored,draftFingerprint(saved));if(!cancelled)setBuilt(build);}catch(e){if(!cancelled)setStatus(String(e));}}}catch(e){if(!cancelled)setError("Draft could not be restored: "+String(e));}finally{if(!cancelled)setReady(true);}})();return()=>{cancelled=true;};},[]);
 useEffect(()=>{setTab(mode==="compile"?"build":mode==="simulate"?"run":"inspect");},[mode]);
 useEffect(()=>{const changed=(e:StorageEvent)=>{if(e.key===KEY||e.key===BUILD_KEY){generation.current++;runtime.current=null;setRunning(false);setBuilt(null);setReplay(null);setActions({});setEvents([]);setError("The workflow changed in another tab. Reload this page to load the current draft and compiled package.");}};window.addEventListener("storage",changed);return()=>window.removeEventListener("storage",changed);},[]);
 function go(path:string){if(!ready)return;try{localStorage.setItem(KEY,JSON.stringify(draftRef.current));window.location.assign(path);}catch{setError("Browser storage unavailable. Save your draft before leaving this page.");}}
 function saveBuild(record:{pkg:ComposePackage;fingerprint:string;hash:string},source:Draft){localStorage.setItem(KEY,JSON.stringify(source));localStorage.setItem(BUILD_KEY,JSON.stringify(record));setBuilt(record);}

 useEffect(()=>{if(ready)fit();},[ready]); // initial viewport only
 useEffect(()=>{const controller=new AbortController();fetch("/api/library",{signal:controller.signal}).then(r=>r.json()).then(r=>setLibrary(r.items??[])).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{generation.current++;runtime.current=null;setRunning(false);setActions({});setEvents([]);setEvent(null);setReplay(null);setReplayResult("");setTick(0);},[fingerprint]);
 const obstacleRef=useRef(obstacle);obstacleRef.current=obstacle;
 async function step(count=5){
  if(stepping.current||!active?.pkg.manifest.executable)return;stepping.current=true;const gen=generation.current;
  try{if(!runtime.current){const loaded=await loadCompiledStack(active.pkg);if(gen!==generation.current)return;runtime.current=loaded;}if(gen!==generation.current)return;let latest:Awaited<ReturnType<CompiledStack["step"]>>|undefined;const batch:RuntimeEvent[]=[];
   for(let i=0;i<count;i++){latest=await runtime.current!.step(scenarioInput(active.pkg,obstacleRef.current));if(gen!==generation.current)return;batch.push(...latest.events);if(latest.replay){setReplay(latest.replay);setReplayResult("");}}
   if(latest){setTick(latest.tick+1);setActions(latest.actions);setEvents(prev=>[...prev,...batch].slice(-200));}
  }catch(e){setError(String(e));setRunning(false);}finally{stepping.current=false;}
 }
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>void step(20),50);return()=>clearInterval(timer);},[running,active]);
 function resetRun(){generation.current++;runtime.current=null;setRunning(false);setEvents([]);setActions({});setEvent(null);setReplay(null);setReplayResult("");setTick(0);}
 async function compile(){
  resetRun();setBusy(true);setError("");const snap=draftRef.current,key=draftFingerprint(snap);
  try{const pkg=await buildStack(snap.graph,async k=>{if(Object.hasOwn(snap.modules,k))return snap.modules[k];const n=snap.graph.nodes.find(n=>DEFINITIONS[n.type].module&&moduleKey(n)===k)!;const url=n.module?"/api/library/"+n.module.id+"/files?version="+encodeURIComponent(n.module.version)+"&path=block.json":"/blocks/"+k+"/1.0.0/block.json";const r=await fetch(url);if(!r.ok)throw Error("Could not load "+k);return r.text();});const hash=await digest(canonical(pkg));if(fingerRef.current!==key){setStatus("Graph changed during build. Build again.");return;}saveBuild({pkg,fingerprint:key,hash},snap);setTab(mode==="simulate"?"run":"build");setStatus(pkg.manifest.executable?"Executable browser package built":"Source package built; runtime interfaces unresolved");
  }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}
 }
 async function importFile(file?:File){if(!file)return;setError("");try{if(file.size>20_000_000)throw Error("File exceeds 20 MB.");const raw=await file.text(),value=JSON.parse(raw);if(value.format==="synapsevm.compose-draft.v1"){const saved=checkedDraft(value.draft);commit(saved);setStatus("Draft imported");return;}const pkg=await importStack(raw);commit({graph:pkg.graph,positions:layout(pkg.graph),modules:pkg.modules});saveBuild({pkg,fingerprint:draftFingerprint({graph:pkg.graph,modules:pkg.modules}),hash:await digest(canonical(pkg))},{graph:pkg.graph,positions:layout(pkg.graph),modules:pkg.modules});setTab(mode==="simulate"?"run":"build");setStatus("Package checked; exact module bytes retained");setTimeout(()=>fit(layout(pkg.graph)),0);}catch(e){setError(String(e));}}
 useEffect(()=>{if(!ready)return;const p=new URLSearchParams(window.location.search),repo=p.get("repository");if(!repo)return;setBuilt(null);setBusy(true);const controller=new AbortController();fetch("/api/library/"+repo+"/files?path=stack.synapse&version="+encodeURIComponent(p.get("version")??""),{signal:controller.signal}).then(r=>{if(!r.ok)throw Error("Published Stack unavailable");return r.text();}).then(async raw=>{const pkg=await importStack(raw);if(controller.signal.aborted)return;commit({graph:pkg.graph,positions:layout(pkg.graph),modules:pkg.modules});saveBuild({pkg,fingerprint:draftFingerprint({graph:pkg.graph,modules:pkg.modules}),hash:await digest(canonical(pkg))},{graph:pkg.graph,positions:layout(pkg.graph),modules:pkg.modules});setTab(mode==="simulate"?"run":"build");setTimeout(()=>fit(layout(pkg.graph)),0);}).catch(e=>{if(!controller.signal.aborted)setError(String(e));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[ready]);
 function add(type:string){const current=draftRef.current;let id=type,suffix=2;while(current.graph.nodes.some(n=>n.id===id))id=type+"_"+suffix++;const rect=stage.current;const next={...current,graph:{...current.graph,nodes:[...current.graph.nodes,{id,type}]},positions:{...current.positions,[id]:{x:((rect?.clientWidth??600)/2-pan.x)/zoom,y:((rect?.clientHeight??400)/2-pan.y)/zoom}}};commit(next);setSelected(id);setEdgeIndex(null);setTab("inspect");}
 useEffect(()=>{if(!ready||mode!=="compose")return;const query=new URLSearchParams(window.location.search);if(query.get("template")==="biopilot"){selectTemplate("biopilot");window.history.replaceState(null,"","/compose");return;}const id=query.get("block"),version=query.get("version");if(!id)return;const controller=new AbortController();void(async()=>{try{if(!version)throw Error("Choose a versioned release in Explore first.");const base="/api/library/"+id;const response=await fetch(base+"?version="+encodeURIComponent(version),{signal:controller.signal});if(!response.ok)throw Error("Selected release is unavailable.");const {item}=await response.json() as {item:LibraryItem};if(!canComposeBlock(item))throw Error("This release does not expose the supported four-channel reflex interface.");const file=await fetch(base+"/files?path=block.json&version="+encodeURIComponent(version),{signal:controller.signal});if(!file.ok)throw Error("Selected model bytes unavailable.");const raw=await file.text();if(await digest(raw)!==item.modelDigest)throw Error("Selected release digest does not match its model bytes.");if(!controller.signal.aborted)setRelease({item,raw});}catch(e){if(!controller.signal.aborted)setError(String(e));}})();return()=>controller.abort();},[ready,mode]);
 function useRelease(start:boolean){if(!release)return;const {item,raw}=release,current=draftRef.current;const g=start?template():structuredClone(current.graph);let id="LoomGuard";if(!start){let suffix=2;while(g.nodes.some(n=>n.id===id))id="LoomGuard_"+suffix++;g.nodes.push({id,type:"LoomGuard"});}g.nodes=g.nodes.map(n=>n.id===id?{...n,module:{id:item.id,version:item.version,digest:item.modelDigest!}}:n);const pos=start?layout(g):{...current.positions,[id]:{x:80,y:80}};commit({graph:g,positions:pos,modules:{...start?{}:current.modules,[item.id+"@"+item.version]:raw}});setSelected(id);setEdgeIndex(null);setRelease(null);setStatus("Pinned "+item.id+"@"+item.version);window.history.replaceState(null,"","/compose");setTimeout(()=>fit(pos),0);}
 function removeNode(){if(!node)return;const next={...graph,nodes:graph.nodes.filter(n=>n.id!==node.id),edges:graph.edges.filter(e=>!e.from.startsWith(node.id+".")&&!e.to.startsWith(node.id+"."))};updateGraph(next);setSelected("");}
 function connect(to:string){if(!pending){setError("Select an output port first, then an input.");return;}const problem=connectionProblem(graph,pending,to);if(problem){const adapters=suggestAdapter(graph,pending,to);setAdapterOffer(adapters.length?{from:pending,to,types:adapters}:null);setError(problem+(adapters.length?" Insert adapter: "+adapters.join(", ")+".":""));return;}updateGraph({...graph,edges:[...graph.edges,{from:pending,to,mode:"LATEST"}]});}
 function insertAdapter(type:string){
 if(!adapterOffer)return;let id=type,suffix=2;while(graph.nodes.some(n=>n.id===id))id=type+"_"+suffix++;
 const d=DEFINITIONS[type],edges=[...graph.edges,{from:adapterOffer.from,to:id+"."+Object.keys(d.inputs)[0],mode:"LATEST" as const},{from:id+"."+Object.keys(d.outputs)[0],to:adapterOffer.to,mode:"LATEST" as const}],next={...graph,nodes:[...graph.nodes,{id,type}],edges};
 const problem=checkGraph(next).errors.find(e=>e.code==="CYCLE"||(e.edge!==undefined&&e.edge>=graph.edges.length));if(problem){setError(problem.message+" Remove the existing input connection first.");return;}
 const a=anchor(adapterOffer.from,true),b=anchor(adapterOffer.to,false);commit({...draft,graph:next,positions:{...positions,[id]:{x:(a.x+b.x)/2,y:(a.y+b.y)/2+150}}});setSelected(id);
 }
 function setParam(key:string,value:number){if(!node)return;updateGraph({...graph,nodes:graph.nodes.map(n=>n.id===node.id?{...n,params:{...n.params,[key]:value}}:n)});}
 function selectTemplate(kind:string){const g=template(kind),pos=layout(g);commit({graph:g,positions:pos,modules:{}});setSelected(g.nodes.find(n=>n.type==="LoomGuard")?.id??"");setEdgeIndex(null);setTimeout(()=>fit(pos),0);}
 function anchor(port:string,out:boolean){const [id,name]=port.split("."),n=graph.nodes.find(n=>n.id===id);if(!n)return {x:0,y:0};const d=DEFINITIONS[n.type],p=positions[id]??{x:0,y:0};return {x:p.x+(out?235:0),y:p.y+88+Object.keys(out?d.outputs:d.inputs).indexOf(name)*27};}
 function onDown(n:ComposeNode,e:PointerEvent){if(e.button!==0)return;e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);const p=positions[n.id]??{x:0,y:0};drag.current={id:n.id,px:e.clientX,py:e.clientY,x:p.x,y:p.y,original:draftRef.current};setSelected(n.id);setEdgeIndex(null);setTab("inspect");}
 function onMove(e:PointerEvent){const d=drag.current;if(!d)return;setDraft(old=>({...old,positions:{...old.positions,[d.id]:{x:d.x+(e.clientX-d.px)/zoom,y:d.y+(e.clientY-d.py)/zoom}}}));}
 function onUp(){const d=drag.current;if(d){if(canonical(d.original.positions)!==canonical(draftRef.current.positions)){setPast(p=>[...p.slice(-29),d.original]);setFuture([]);}persistDraft(draftRef.current);drag.current=null;}}
 const available=library.filter(i=>i.kind==="NeuroBlock"&&canonical(i.actualInputs)===canonical(["depth_front","depth_left","depth_right","loom"])&&i.modelDigest);
 return <div className={"cmp cmp-mode-"+mode}>
 <nav className="cmp-flow" aria-label="Build workflow">{[["explore","Explore","Choose a release"],["compose","Compose","Wire the graph"],["compile","Compile","Lock an artifact"],["simulate","Simulate","Test that artifact"]].map(([key,label,hint],i)=><button key={key} aria-current={mode===key?"step":undefined} onClick={()=>go("/"+key)}><b>{i+1} · {label}</b><small>{hint}</small></button>)}</nav>
 <div className="cmp-flow-summary"><strong>{mode==="compose"?"Design your controller":mode==="compile"?"Compile the current graph":"Simulate the compiled Stack"}</strong><p>{mode==="compose"?"Choose versioned modules, wire explicit adapters, then continue to Compile.":mode==="compile"?"Check the graph, resolve exact model bytes, and produce the package used by Simulate.":"Run the locked package below. Return to Compose to change behavior, then compile a new build."}</p>{mode==="simulate"&&<Link href="/simulate?mode=demo">Browse bundled Block demos →</Link>}</div>
 {release&&<div className="cmp-alert"><div><strong>{release.item.id}@{release.item.version}</strong><p>Exact release loaded from Explore. Add it to your graph, or start a connected Collision Shield using this release.</p></div><button onClick={()=>useRelease(false)}>Add to current graph</button><button onClick={()=>useRelease(true)}>Start a connected Stack</button><button onClick={()=>setRelease(null)}>Dismiss</button></div>}
 {!ready&&<p role="status">Loading workflow…</p>}
 <header className="cmp-toolbar"><div><span className="cmp-eyebrow">NEUROSTACK WORKBENCH</span><div className="cmp-title"><input readOnly={mode!=="compose"} aria-label="Stack name" value={graph.name} onChange={e=>updateGraph({...graph,name:e.target.value})}/><span>@</span><input readOnly={mode!=="compose"} aria-label="Stack version" value={graph.version} onChange={e=>updateGraph({...graph,version:e.target.value})}/></div></div>
 <div className="cmp-tools"><button onClick={undo} disabled={!past.length} title="Undo">↶ Undo</button><button onClick={redo} disabled={!future.length} title="Redo">↷ Redo</button><label className="cmp-file">Import<input type="file" accept=".synapse,.json" aria-label="Import Stack or draft" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value="";}}/></label><button onClick={()=>download(graph.name+".draft.json",JSON.stringify({format:"synapsevm.compose-draft.v1",draft},null,2))}>Save draft</button><button className="primary" disabled={!ready||busy||validation.errors.length>0} onClick={()=>mode==="compose"?go("/compile"):void compile()}>{mode==="compose"?"Continue to Compile":busy?"Compiling…":"Compile Stack"}</button><button className="run" disabled={!ready||!active?.pkg.manifest.executable} onClick={()=>go("/simulate")}>Open in Simulate →</button></div>
 </header>
 <div className="cmp-status"><span className={validation.errors.length?"bad":"good"}>{validation.errors.length?validation.errors.length+" issues":"Graph valid"}</span><span>{graph.nodes.length} nodes · {graph.edges.length} connections</span><span>{active?(active.pkg.manifest.executable?"Built · executable JS":"Built · source only"):"Unbuilt changes"}</span><span>{status}</span></div>
 {error&&<div role="alert" className="cmp-alert"><span>{error}</span>{adapterOffer?.types.map(t=><button key={t} onClick={()=>insertAdapter(t)}>Insert {t}</button>)}<button aria-label="Dismiss error" onClick={()=>setError("")}>×</button></div>}
 <div className="cmp-workspace">
 <aside className="cmp-palette"><h2>Building blocks</h2><p>Typed pieces. Explicit behavior.</p><label>Start from a template<select aria-label="Template" defaultValue="shield" onChange={e=>selectTemplate(e.target.value)}><option value="shield">Collision Shield · executable</option><option value="brake">Emergency Brake · executable</option><option value="arbiter">Safety Override · executable</option><option value="biopilot">BioPilot · source template</option><option value="empty">Empty canvas</option></select></label><input aria-label="Search nodes" placeholder="Find a node…" value={search} onChange={e=>setSearch(e.target.value)}/>
 {families.map(f=><section key={f}><h3>{f==="neuroblock"?"NEUROBLOCKS":f.toUpperCase()}</h3>{Object.entries(DEFINITIONS).filter(([name,d])=>d.family===f&&(name+" "+d.description).toLowerCase().includes(search.toLowerCase())).map(([type,d])=><button className={"cmp-add family-"+f} key={type} onClick={()=>add(type)} title={d.description}><span>{type}</span><small>{d.unsupported?"Source interface":f==="neuroblock"?"Locked neural model":d.stateful?"Stateful · deterministic":"Deterministic"}</small><b>+</b></button>)}</section>)}
 <div className="cmp-trust-note"><strong>Trust stays outside the loop</strong><p>Receipts and replay run after the control decision. No network service sits between a sensor and an actuator.</p></div>
 </aside>
 <section className="cmp-center">
 <div className="cmp-canvas-tools"><span>{pending?"Connect "+pending+" to an input":"Select an output, then an input to connect"}</span>{pending&&<button onClick={()=>setPending("")}>Cancel wire</button>}<button onClick={()=>{const pos=layout(graph);commit({...draft,positions:pos});fit(pos);}}>Auto layout</button><button onClick={()=>fit()}>Fit</button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.2,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}>+</button></div>
 <div ref={stage} className="cmp-stage" aria-label="Composition canvas" onPointerDown={e=>{if(e.target!==e.currentTarget)return;panDrag.current={px:e.clientX,py:e.clientY,...pan};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const p=panDrag.current;if(p)setPan({x:p.x+e.clientX-p.px,y:p.y+e.clientY-p.py});}} onPointerUp={()=>{panDrag.current=null;}} onPointerCancel={()=>{panDrag.current=null;drag.current=null;}}>
 <div className="cmp-transform" style={{transform:"translate("+pan.x+"px,"+pan.y+"px) scale("+zoom+")"}}>
 <svg className="cmp-wires" aria-label="Graph connections">{graph.edges.map((e,i)=>{const a=anchor(e.from,true),b=anchor(e.to,false),dx=Math.max(55,Math.abs(b.x-a.x)*.45),path="M "+a.x+" "+a.y+" C "+(a.x+dx)+" "+a.y+", "+(b.x-dx)+" "+b.y+", "+b.x+" "+b.y;return <g key={e.from+e.to+i}><path className={edgeIndex===i?"selected":""} d={path}/><path className="hit" d={path} role="button" tabIndex={0} aria-label={"Inspect connection "+e.from+" to "+e.to} onClick={()=>{setEdgeIndex(i);setSelected("");setTab("inspect");}} onKeyDown={ev=>{if(ev.key==="Enter"){setEdgeIndex(i);setSelected("");setTab("inspect");}}}/></g>;})}</svg>
 {graph.nodes.map(n=>{const d=DEFINITIONS[n.type],p=positions[n.id]??{x:0,y:0},lit=events.slice(-12).some(e=>e.node===n.id&&e.tick>=tick-6);return <article key={n.id} style={{left:p.x,top:p.y}} className={"cmp-node family-"+d.family+(selected===n.id?" selected":"")+(lit?" active":"")}>
 <button className="cmp-node-head" onPointerDown={e=>onDown(n,e)} onPointerMove={onMove} onPointerUp={onUp} onPointerCancel={onUp} onClick={()=>{setSelected(n.id);setEdgeIndex(null);setTab("inspect");}}><small>{d.family} · P{d.priority}</small><strong>{n.id}</strong><span>{paramsFor(n).hz} Hz · {d.stateful?"stateful":"stateless"}{d.unsupported?" · source":""}</span></button>
 <div className="cmp-ports"><div>{Object.entries(d.inputs).map(([port,type])=><button key={port} title={type} aria-label={"Connect input "+n.id+"."+port} onClick={()=>connect(n.id+"."+port)}><i/>{port}</button>)}</div><div>{Object.entries(d.outputs).map(([port,type])=><button key={port} title={type} className={pending===n.id+"."+port?"pending":""} aria-label={"Select output "+n.id+"."+port} onClick={()=>{setPending(n.id+"."+port);setError("");}}>{port}<i/></button>)}</div></div></article>;})}
 </div>{!graph.nodes.length&&<div className="cmp-empty">Add a sensor, a neural module, and an actuator to start.</div>}
 </div>
 <ComposeAssistant onApply={applyPlan}/>
  <section className="cmp-diagnostics"><div><h3>Build checks</h3><span>{validation.estimatedMs.toFixed(1)} ms estimated compute path · {graph.deadlineMs} ms budget</span></div>{validation.errors.length?validation.errors.map((e,i)=><button className="bad" key={i} onClick={()=>{if(mode!=="compose"){go("/compose");return;}if(e.node)setSelected(e.node);if(e.edge!==undefined)setEdgeIndex(e.edge);setTab("inspect");}}><b>{e.code}</b> {e.message}</button>):<p className="good">Types, required inputs, writers, cycles, parameters and timing checked.</p>}{validation.warnings.map((e,i)=><p key={i}>{e.message}</p>)}{validation.blocked.map((e,i)=><p className="cmp-warning" key={i}><b>Runtime unavailable:</b> {e.message}</p>)}</section>
 <section className="cmp-timeline"><header><h3>Execution timeline</h3><span>{events.length?events.length+" recent node events":"Run a built graph to record events"}</span></header><div>{events.slice(-30).reverse().map((e,i)=><button key={e.tick+"-"+e.node+"-"+i} onClick={()=>{setEvent(e);setTab("run");}}><code>{e.tick} ms</code><strong>{e.node}</strong><span className={e.type==="SAFETY_OVERRIDE"||e.type==="TRIGGER"?"bad":""}>{e.type}</span></button>)}</div></section>
 </section>
 <aside className="cmp-inspector"><nav hidden={mode!=="compose"}>{(["inspect","build","run"] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==="inspect"?"Inspector":t==="build"?"Compile & export":"Quick preview"}</button>)}</nav>
 {tab==="inspect"&&<>
 {edge?<><span className="cmp-eyebrow">CONNECTION</span><h2>{edge.from.split(".")[0]} → {edge.to.split(".")[0]}</h2><code>{edge.from}<br/>↓<br/>{edge.to}</code><dl><dt>Delivery</dt><dd>LATEST · held until updated</dd><dt>Buffer</dt><dd>One latest value</dd><dt>Conversion</dt><dd>None. Add an explicit adapter.</dd></dl><button className="danger" onClick={()=>{updateGraph({...graph,edges:graph.edges.filter((_,i)=>i!==edgeIndex)});setEdgeIndex(null);}}>Delete connection</button></>:node&&nodeDef?<><span className="cmp-eyebrow">{nodeDef.family} · {nodeDef.module?"NEURAL MODEL":"CONVENTIONAL SOFTWARE"}</span><h2>{node.id}</h2><p>{nodeDef.description}</p><dl><dt>State</dt><dd>{nodeDef.stateful?"Stateful · captured for replay":"Stateless"}</dd><dt>Priority</dt><dd>P{nodeDef.priority} {nodeDef.priority===0?"Critical":"Control / perception"}</dd><dt>Compute estimate</dt><dd>{nodeDef.ms} ms · unmeasured</dd><dt>Execution</dt><dd>{nodeDef.unsupported?"Source interface only":"Deterministic JavaScript"}</dd></dl><label>Update rate<select aria-label="Node update rate" value={paramsFor(node).hz} onChange={e=>setParam("hz",Number(e.target.value))}>{RATES.map(hz=><option key={hz} value={hz}>{hz} Hz</option>)}</select></label>{Object.entries(nodeDef.params).map(([key,spec])=><label key={key}>{spec.label}<input type="number" min={spec.min} max={spec.max} value={paramsFor(node)[key]} onChange={e=>setParam(key,Number(e.target.value))}/></label>)}
 {node.type==="LoomGuard"&&<label>Locked Library release<select aria-label="LoomGuard release" value={node.module?node.module.id+"@"+node.module.version:"bundled"} onChange={e=>{const item=available.find(i=>i.id+"@"+i.version===e.target.value);updateGraph({...graph,nodes:graph.nodes.map(n=>n.id===node.id?{id:n.id,type:n.type,params:n.params??{},...item?{module:{id:item.id,version:item.version,digest:item.modelDigest!}}:{}}:n)});}}><option value="bundled">Bundled LoomGuard · 1.0.0</option>{available.map(i=><option key={i.id} value={i.id+"@"+i.version}>{i.id}@{i.version}</option>)}</select></label>}
 <h3>Port contracts</h3>{Object.entries(nodeDef.inputs).map(([p,t])=><p className="cmp-contract" key={p}><b>IN · {p}</b><code>{t}</code></p>)}{Object.entries(nodeDef.outputs).map(([p,t])=><p className="cmp-contract" key={p}><b>OUT · {p}</b><code>{t}</code></p>)}{nodeDef.module&&<Link href={"/explore/"+(node.module?.id??"synapsevm/"+nodeDef.module)+(node.module?"?version="+node.module.version:"")}>Open Library repository ↗</Link>}<button className="danger" onClick={removeNode}>Delete node and connections</button></>:<><h2>Inspect a piece</h2><p>Select a node or connection on the canvas.</p></>}
 <hr/><h3>Stack settings</h3><label>Estimated compute deadline (ms)<input type="number" min=".1" max="1000" step=".1" value={graph.deadlineMs} onChange={e=>updateGraph({...graph,deadlineMs:Number(e.target.value)})}/></label><label>Receipt policy<select aria-label="Receipt policy" value={graph.policy} onChange={e=>updateGraph({...graph,policy:e.target.value as ComposeGraph["policy"]})}><option value="FAST">FAST · no receipts</option><option value="AUDIT">AUDIT · critical output changes</option><option value="DEBUG">DEBUG · every executed tick</option></select></label><p className="cmp-small">Rates use a 1 ms deterministic clock. Inputs are recorded Q16.16 features. Estimates exclude acquisition, waiting for scheduled updates, and hardware latency.</p>
 </>}
 {tab==="build"&&<><span className="cmp-eyebrow">BUILD ARTIFACT</span><h2>{active?"A graph with an identity.":"Build your current graph."}</h2>{active?<><p className={active.pkg.manifest.executable?"good":"cmp-warning"}>{active.pkg.manifest.executable?"Executable in the browser and standalone JavaScript.":"Source only: unresolved neural output interfaces."}</p><h3>Stack ID</h3><code className="cmp-hash">{active.pkg.manifest.stackId}</code><h3>Package SHA-256</h3><code className="cmp-hash">{active.hash}</code><h3>Locked dependencies</h3>{Object.entries(active.pkg.lockfile).map(([k,v])=><p className="cmp-contract" key={k}><b>{k.includes("@")?k:k+"@"+v.version}</b><code>{short(v.digest)}</code></p>)}<h3>Execution schedule</h3><ol>{active.pkg.runtimePlan.order.map(id=><li key={id}>{id}<small> every {active.pkg.runtimePlan.periods[id]} ms</small></li>)}</ol><button className="primary" onClick={()=>download(graph.name+"-"+graph.version+".synapse",canonical(active.pkg))}>Download .synapse</button><a className="cmp-download" href="/runtime/compose-runtime.mjs" download>Download JavaScript runtime</a><button onClick={()=>{try{sessionStorage.setItem("synapsevm.publish.stack",canonical(active.pkg));window.location.assign("/explore/publish?compose=1");}catch{setError("Could not transfer package. Download it, then upload in Library.");}}}>Publish to local Library</button><p className="cmp-small">WASM, Rust and ROS2 graph exports are not implemented. This release contains a portable JavaScript execution plan and locked model bytes.</p><details><summary>Use outside this website</summary><pre>{'import { loadCompiledStack, scenarioInput } from "./compose-runtime.mjs";\nimport { readFile } from "node:fs/promises";\nconst pkg = JSON.parse(await readFile("'+graph.name+'-'+graph.version+'.synapse", "utf8"));\nconst stack = await loadCompiledStack(pkg);\n// Synthetic recorded stimulus; replace with sensor inputs.\nconst result = await stack.step(scenarioInput(pkg, false));\nconsole.log(result.actions);'}</pre></details></>:<p>No current compiled artifact. Compile Stack to resolve dependencies and produce the package. Graph or module changes require a new build.</p>}</>}
 {tab==="run"&&<><span className="cmp-eyebrow">LOCAL EXECUTION</span><h2>Follow the actual decision.</h2>{active&&<><p>{active.pkg.manifest.name}@{active.pkg.manifest.version}</p><code className="cmp-hash">Package {active.hash}</code></>}{!active?.pkg.manifest.executable?<p>No current executable package. Compile the current draft first. <button onClick={()=>go("/compile")}>Go to Compile →</button></p>:<><World actions={actions} obstacle={obstacle} tick={tick}/><div className="cmp-run-buttons"><button className="primary" onClick={()=>setRunning(v=>!v)}>{running?"Pause":"Run"}</button><button disabled={running} onClick={()=>void step()}>Step 5 ms</button><button onClick={resetRun}>Reset</button></div><label className="cmp-toggle"><input type="checkbox" checked={obstacle} onChange={e=>setObstacle(e.target.checked)}/> Inject looming obstacle</label><p className="cmp-small">Synthetic, recorded four-channel stimulus. The preview displays graph commands; it is not a physics or hardware benchmark.</p><h3>Actuator outputs · Q16.16</h3><pre>{JSON.stringify(actions,null,2)}</pre>
 <div className="cmp-trust-note"><h3>Receipt & replay</h3><p>{replay?"Critical decision captured with input, pre-state, graph identity and final action.":"No receipt yet. AUDIT records critical output changes; DEBUG records every executed tick."}</p>{replay&&<><code>{short(replay.receipt.hash)}</code><button onClick={async()=>{setRunning(false);try{await replayStack(active.pkg,replay);setReplayResult("MATCH · fresh local runtime reproduced input/state commitments, neural events, control decisions and actuator outputs.");}catch(e){setReplayResult(String(e));}}}>Replay in fresh runtime</button><button onClick={()=>{try{sessionStorage.setItem("synapsevm.verify.stack",JSON.stringify({package:active.pkg,evidence:replay}));window.location.assign("/verify?evidence=compose");}catch{setError("Storage unavailable. Download the Stack and replay, then upload both in Verify.");}}}>Open in Verify</button><button onClick={()=>download(graph.name+".replay.json",canonical(replay))}>Download replay bundle</button><p role="status">{replayResult}</p></>}</div>
 {event&&<section className="cmp-why"><h3>WHY · {event.node}</h3><p>{event.tick} ms · {event.detail}</p>{event.moduleId&&<code>{event.moduleId}</code>}<h4>Inputs received</h4><pre>{JSON.stringify(event.inputs,null,2)}</pre><h4>Outputs produced</h4><pre>{JSON.stringify(event.outputs,null,2)}</pre>{event.fired!==undefined&&<p>{event.fired} neurons fired; first trace IDs: {event.trace?.join(", ")}</p>}</section>}</>}</>}
 </aside></div>
 </div>;
}
