"use client";
import {importStack} from "@/lib/composeCompiler";

import Link from "next/link";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {repoHref,formatBytes,type LibraryItem} from "@/lib/library";
import type {PublishInput} from "@/lib/libraryServer";
import {LibraryIcon as Icon} from "./LibraryIcon";
export function PublishRelease({items}:{items:LibraryItem[]}){
 const [body,setBody]=useState<PublishInput>({owner:"local-lab",name:"",version:"0.1.0",description:"",task:"Collision avoidance",license:"Not specified",readme:"",provenance:"",kind:"NeuroBlock",artifact:"",testVectors:"[]",parent:null});
 const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState<LibraryItem|null>(null);const [published,setPublished]=useState<LibraryItem|null>(null);const [fileName,setFileName]=useState("");const requestRef=useRef(0);
 const update=<K extends keyof PublishInput>(key:K,value:PublishInput[K])=>{setBody(b=>({...b,[key]:value}));setPreview(null);setError("");};
 const loadBase=async(item:LibraryItem,newRelease=false)=>{
  const request=++requestRef.current;setLoading(true);setError("");setPreview(null);
  try{const file=item.kind==="NeuroBlock"?"block.json":item.files.find(f=>f.name.endsWith(".synapse"))?.name;if(!file)throw new Error("This source template has no compiled .synapse package. Export one from Workbench first.");
   const res=await fetch("/api/library/"+item.owner+"/"+item.slug+"/files?version="+item.version+"&path="+encodeURIComponent(file));if(!res.ok)throw new Error("Could not load base artifact");const artifact=await res.text();if(request!==requestRef.current)return;
   const model=JSON.parse(artifact);setBody(b=>({...b,owner:newRelease?item.owner:b.owner,name:newRelease?item.slug:item.slug+"-fork",version:newRelease?item.version.split(".").map((v,i)=>i===2?String(Number(v)+1):v).join("."):"0.1.0",kind:item.kind as PublishInput["kind"],description:item.description,task:item.task,license:item.license,artifact,readme:item.readme,provenance:"Based on "+item.id+"@"+item.version+". "+(item.sourceType==="Engineered"?"Engineered demonstration topology.":"Source attribution is inherited; no independent reproduction is claimed."),testVectors:JSON.stringify([{name:"quiet-input",input:item.kind==="NeuroBlock"?model.inputChannels.map(()=>0):[],ticks:1}],null,2),parent:{id:item.id,version:item.version,digest:item.digest}}));setFileName(file);
  }catch(e){setError(e instanceof Error?e.message:String(e));}finally{if(request===requestRef.current)setLoading(false);}
 };
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const id=p.get("fork");if(!id)return;const item=items.find(i=>i.id===id);if(!item)return;const version=p.get("version");if(version&&version!==item.version){fetch("/api/library/"+id+"?version="+version).then(r=>r.json()).then(j=>{if(j.item)void loadBase(j.item,p.get("release")==="1");else setError(j.error);});}else void loadBase(item,p.get("release")==="1");},[]);
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("compose")!=="1")return;const raw=sessionStorage.getItem("synapsevm.publish.stack");if(!raw)return;setLoading(true);importStack(raw).then(pkg=>{setBody(b=>({...b,artifact:raw,kind:"NeuroStack",name:pkg.graph.name.toLowerCase().replace(/[^a-z0-9_-]/g,"-"),version:pkg.graph.version,description:"A composed neural controller built in SynapseVM.",readme:"This Stack contains an explicit typed graph, locked neural modules and deterministic control settings. "+(pkg.manifest.executable?"Executable with the Compose JavaScript runtime.":"Source-only interfaces remain unresolved."),provenance:"Built in Compose. Locked modules: "+Object.keys(pkg.lockfile).join(", "),testVectors:"[]"}));setFileName(pkg.graph.name+".synapse");}).catch(e=>setError(String(e))).finally(()=>setLoading(false));},[]);
 const upload=async(file?:File)=>{if(!file)return;requestRef.current++;setLoading(false);setPreview(null);setError("");if(file.size>4_000_000){setError("Choose an artifact smaller than 4 MB.");return;}try{const artifact=await file.text();const model=JSON.parse(artifact);const kind=["synapsevm.source-package.v1","synapsevm.compose-package.v1"].includes(model.format)?"NeuroStack":"NeuroBlock";setBody(b=>({...b,artifact,kind,parent:null,testVectors:JSON.stringify(kind==="NeuroBlock"?[{name:"quiet-input",input:(model.inputChannels??[]).map(()=>0),ticks:1}]:[],null,2)}));setFileName(file.name);}catch{setError("That file is not valid JSON.");}};
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/library"+(preview?"":"?preview=1"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const json=await res.json();if(!res.ok)throw new Error(json.error??"Publication failed");if(preview)setPublished(json.item);else setPreview(json.item);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 if(published)return <div className="library-page lib-publish-success"><span className="lib-success-mark"><Icon name="check" size={30}/></span><div className="lib-eyebrow">LOCAL RELEASE CREATED</div><h1>Your module has a home.</h1><p>{published.id}@{published.version} is now in Discover.</p><code className="lib-digest">{published.digest}</code><div><Link className="lib-button primary" href={repoHref(published)}>View repository <Icon name="arrow"/></Link><Link className="lib-button" href={"/explore?kind="+published.kind+"&origin=local"}>Browse local publications</Link></div></div>;
 return <div className="library-page lib-publish"><Link className="lib-back" href="/explore">← Back to Discover</Link><header><div className="lib-eyebrow">CONTRIBUTE A BUILDING BLOCK</div><h1>Publish a release.</h1><p>A clear interface, a traceable source, and an immutable version.</p></header><div className="lib-publish-layout"><form onSubmit={submit}><fieldset disabled={busy||loading}><section><div className="lib-step-title"><span>1</span><h2>Choose your artifact</h2></div><label>Start from a bundled Block<select defaultValue="" onChange={e=>{const item=items.find(i=>i.id===e.target.value);if(item)void loadBase(item);}}><option value="" disabled>Select a starter, or upload below</option>{items.filter(i=>i.kind==="NeuroBlock"&&i.origin==="bundled").map(i=><option key={i.id} value={i.id}>{i.owner}/{i.name} · v{i.version}</option>)}</select></label><label className="lib-upload"><Icon name="upload" size={24}/><strong>{fileName||"Upload block.json or a .synapse source package"}</strong><span>JSON model data · maximum 4 MB</span><input aria-label="Upload artifact" type="file" accept=".json,.synapse" onChange={e=>void upload(e.target.files?.[0])}/></label>{loading&&<p role="status">Loading artifact…</p>}{body.parent&&<p className="lib-parent"><Icon name="fork" size={16}/>Fork of {body.parent.id}@{body.parent.version}</p>}</section>
 <section><div className="lib-step-title"><span>2</span><h2>Give it an identity</h2></div><div className="lib-form-two"><label>Publisher namespace<input required pattern="[a-z0-9][a-z0-9_-]{0,47}" value={body.owner} onChange={e=>update("owner",e.target.value)} placeholder="your-lab"/></label><label>Repository name<input required pattern="[a-z0-9][a-z0-9_-]{0,47}" value={body.name} onChange={e=>update("name",e.target.value)} placeholder="collision-reflex"/></label></div><p className="lib-note">{body.owner}/{body.name||"your-module"} · local, self-declared namespace</p><div className="lib-form-two"><label>Version<input required value={body.version} onChange={e=>update("version",e.target.value)} placeholder="0.1.0"/></label><label>License<select value={body.license} onChange={e=>update("license",e.target.value)}>{["Not specified","MIT","Apache-2.0","CC-BY-4.0","CC0-1.0"].map(l=><option key={l}>{l}</option>)}</select></label></div><label>What does it do?<input required minLength={10} maxLength={280} value={body.description} onChange={e=>update("description",e.target.value)} placeholder="A compact reflex that responds to visual expansion."/></label><label>Task<select value={body.task} onChange={e=>update("task",e.target.value)}>{["Collision avoidance","Optic flow","Navigation","Target tracking","Custom control"].map(t=><option key={t}>{t}</option>)}</select></label></section>
 <section><div className="lib-step-title"><span>3</span><h2>Explain the source & behavior</h2></div><label>Repository overview<textarea required minLength={20} rows={5} value={body.readme} onChange={e=>update("readme",e.target.value)} placeholder="Describe what this module does, how to use it, and its limitations."/></label><label>Provenance statement<textarea required minLength={10} rows={3} value={body.provenance} onChange={e=>update("provenance",e.target.value)} placeholder="Name the source dataset, parent module, or engineering method."/></label>{body.kind==="NeuroBlock"&&<label>Test vectors (JSON)<textarea className="lib-code-input" required rows={7} value={body.testVectors} onChange={e=>update("testVectors",e.target.value)}/><span className="lib-note">Each vector needs a name, one int32 input per channel, and 1–8 ticks. These run as local smoke tests.</span></label>}</section></fieldset>
 {error&&<div className="lib-form-error" role="alert">{error}</div>}{preview&&<section className="lib-preview-release"><h3><Icon name="check"/> Ready for local publication</h3><p>{preview.id}@{preview.version} · {preview.files.length} files · {formatBytes(preview.bytes)}</p><code className="lib-digest">{preview.digest}</code><p>{preview.testsRun?preview.testCount+" smoke tests executed. No independent replay attestation.":"Package integrity checked. Execution tests have not run for this publication."}</p></section>}
 <div className="lib-publish-submit"><button className="lib-button primary" type="submit" disabled={busy||loading||!body.artifact}>{busy?"Checking release…":preview?"Publish locally":"Validate & preview"}<Icon name="arrow" size={17}/></button>{preview&&<button type="button" className="lib-button" onClick={()=>setPreview(null)}>Back to editing</button>}</div></form><aside><div className="lib-community-card"><Icon name="block" size={28}/><h3>A useful release is more than a model.</h3><ul><li>A versioned identity</li><li>Explicit inputs and outputs</li><li>Source and licensing information</li><li>Reproducible test inputs</li><li>Exact file digests</li></ul></div><div className="lib-callout"><div><strong>Local Discover</strong><p>Releases are saved on this machine and survive app restarts. Nothing is sent to a public registry. Publisher names are not authenticated.</p><p>Existing versions cannot be overwritten. Publish a new version when your artifact changes.</p></div></div></aside></div></div>;
}
