"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {formatBytes,releaseDate,repoHref,type LibraryItem} from "@/lib/library";
import {LibraryIcon as Icon} from "./LibraryIcon";
const TABS=["Overview","Biology","Interface","Files","Simulator","Benchmarks","Verification","Versions"];
export function RepositoryDetail({item,initialTab}:{item:LibraryItem;initialTab?:string}){
 const [tab,setTab]=useState(TABS.find(t=>t.toLowerCase()===initialTab)??"Overview");const [file,setFile]=useState("");const [content,setContent]=useState("");const [copied,setCopied]=useState(false);const [fileError,setFileError]=useState("");
 const fileUrl=(name:string)=>"/api/library/"+item.owner+"/"+item.slug+"/files?version="+item.version+"&path="+encodeURIComponent(name);
 useEffect(()=>{if(!file)return;const abort=new AbortController();setContent("");setFileError("");if(file.endsWith(".bin")){setContent("Binary artifact. Download the file to inspect its exact bytes.");return;}
 fetch(fileUrl(file),{signal:abort.signal}).then(async r=>{if(!r.ok)throw new Error("File could not be loaded");return r.text();}).then(text=>setContent(text.length>60000?text.slice(0,60000)+"\n\n… Preview truncated. Download for the full file.":text)).catch(e=>{if(e.name!=="AbortError")setFileError(e.message);});return()=>abort.abort();},[file,item.version,item.id]);
 const chooseTab=(value:string)=>{setTab(value);const p=new URLSearchParams(window.location.search);p.set("tab",value.toLowerCase());window.history.replaceState(null,"",window.location.pathname+"?"+p.toString());};
 const copy=async()=>{try{await navigator.clipboard.writeText(item.digest);setCopied(true);setTimeout(()=>setCopied(false),1500);}catch{setCopied(false);}};
 const publishHref="/explore/publish?fork="+encodeURIComponent(item.id)+"&version="+item.version;
 return <div className="library-page lib-detail">
  <Link className="lib-back" href={"/explore?kind="+item.kind}>← Back to Discover</Link>
  <header className="lib-repository-header"><div className="lib-avatar blue"><Icon name={item.kind==="NeuroStack"?"stack":item.kind==="NeuroBlock"?"block":"source"} size={30}/></div><div className="lib-repository-heading"><div className="lib-eyebrow">{item.kind} · {item.origin==="local"?"LOCAL PUBLICATION":item.origin==="reference"?"SOURCE REFERENCE":"BUNDLED COLLECTION"}</div><h1><Link href={"/explore?kind="+item.kind+"&q="+encodeURIComponent(item.owner)}>{item.owner}</Link><span>/</span>{item.name}</h1><p>{item.description}</p></div><div className="lib-detail-actions">{["NeuroBlock","NeuroStack"].includes(item.kind)&&<Link className="lib-button" href={publishHref}><Icon name="fork" size={16}/> Fork locally</Link>}{item.simulator&&<Link className="lib-button primary" href={"/simulate?block="+item.simulator}>Try in Simulator <Icon name="arrow" size={16}/></Link>}</div></header>
  <div className="lib-detail-tags"><span className="lib-tag task">{item.task}</span><span className="lib-tag">{item.sourceType}</span><span className="lib-tag">{item.runtime}</span><span className="lib-tag">License: {item.license}</span></div>
  <nav className="lib-detail-tabs" aria-label="Repository sections">{TABS.map(t=><button key={t} aria-pressed={tab===t} className={tab===t?"active":""} onClick={()=>chooseTab(t)}>{t}{t==="Files"&&<span>{item.files.length}</span>}{t==="Versions"&&<span>{item.releases.length}</span>}</button>)}</nav>
  <div className="lib-detail-layout"><section className="lib-detail-content" aria-label={tab}>
  {tab==="Overview"&&<><div className="lib-section-head"><h2>Repository card</h2><span className="lib-tag">v{item.version}</span></div><div className="lib-readme">{item.readme.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}</div><h3>At a glance</h3><div className="lib-facts"><div><small>Artifact type</small><strong>{item.kind}</strong></div><div><small>Package size</small><strong>{formatBytes(item.bytes)}</strong></div><div><small>Neurons / synapses</small><strong>{item.neurons===null?"Not applicable":item.neurons.toLocaleString()+" / "+item.synapses?.toLocaleString()}</strong></div><div><small>Test vectors</small><strong>{item.testCount?item.testCount+" included":"Not included"}</strong></div></div><div className="lib-callout"><Icon name="code"/><div><strong>Inspect before composing</strong><p>Review the runtime interface and source lineage. A package digest identifies bytes; it does not establish scientific validity or deployment safety.</p><button onClick={()=>chooseTab("Interface")}>Explore the interface →</button></div></div>{item.parent&&<div className="lib-parent"><Icon name="fork"/>Forked from <Link href={"/explore/"+item.parent.id+"?version="+item.parent.version}>{item.parent.id}@{item.parent.version}</Link><code>{item.parent.digest}</code></div>}</>}
  {tab==="Biology"&&<><h2>Source lineage</h2><p className="lib-muted">Follow the evidence from source material to executable model choices.</p><div className="lib-lineage">{item.lineage.map((node,i)=><div key={i}><span className="lib-lineage-marker">{i+1}</span><div><small>{node.kind}</small><h3>{node.href?<Link href={node.href}>{node.name}</Link>:node.name}</h3><p>{node.note}</p></div></div>)}</div><div className="lib-callout"><Icon name="source"/><p>Source attribution and engineered dynamics are separate claims. No independent biological reproduction is attached to this release.</p></div></>}
  {tab==="Interface"&&<><h2>Inputs & outputs</h2><p className="lib-muted">The public contract describes the intended module. Runtime channels below come from the actual artifact.</p><div className="lib-port-grid"><section><h3>Input contract</h3>{item.inputs.map(p=><code key={p}>{p}</code>)}{!item.inputs.length&&<p>No runtime inputs.</p>}</section><span>→</span><section><h3>Output contract</h3>{item.outputs.map(p=><code key={p}>{p}</code>)}{!item.outputs.length&&<p>No runtime outputs.</p>}</section></div>{item.actualInputs.length>0&&<><h3>Current runtime ABI</h3><table className="lib-table"><thead><tr><th>Direction</th><th>Channels, in order</th><th>Encoding</th></tr></thead><tbody><tr><td>Input</td><td>{item.actualInputs.join(", ")}</td><td>int32 Q16.16</td></tr><tr><td>Output</td><td>{item.actualOutputs.join(", ")}</td><td>Q16.16 / trigger 0–1</td></tr></tbody></table><p className="lib-note">Typed application adapters are still required where the public contract differs from the runtime channels.</p><h3>Quiet input example</h3><pre className="lib-code">{JSON.stringify({input:item.actualInputs.map(()=>0),ticks:1},null,2)}</pre></>}</>}
  {tab==="Files"&&<><div className="lib-section-head"><h2>Files & artifacts</h2><span className="lib-tag">{formatBytes(item.bytes)} total</span></div><p className="lib-muted">Every file has an independently computed SHA-256 digest.</p><div className="lib-file-list">{item.files.map(f=><div key={f.name}><button onClick={()=>setFile(f.name)} className={file===f.name?"active":""}><Icon name="file" size={17}/>{f.name}</button><span>{formatBytes(f.bytes)}</span><a href={fileUrl(f.name)+"&download=1"} download aria-label={"Download "+f.name}>↓</a></div>)}</div>{file&&<section className="lib-file-preview"><div className="lib-section-head"><strong>{file}</strong><button onClick={()=>setFile("")} aria-label="Close file preview"><Icon name="close" size={16}/></button></div><code className="lib-digest">{item.files.find(f=>f.name===file)?.digest}</code><pre>{fileError||content||"Loading file…"}</pre></section>}</>}
  {tab==="Simulator"&&<><h2>Try the behavior</h2><p className="lib-muted">Test the selected module in the local demonstration environment.</p>{item.simulator?<div className="lib-simulator-card"><div className="lib-mini-graph"><Icon name="source" size={28}/><Icon name="arrow"/><Icon name="block" size={28}/><Icon name="arrow"/><Icon name="stack" size={28}/></div><h3>{item.name} scenarios</h3><p>The simulator loads this bundled Block with embodiment-specific demonstration adapters.</p><Link className="lib-button primary" href={"/simulate?block="+item.simulator}>Open Simulator <Icon name="arrow" size={16}/></Link></div>:<div className="lib-empty"><Icon name="block" size={30}/><h3>No simulator adapter attached</h3><p>This release can be inspected and downloaded. A runnable simulator mapping has not been registered.</p></div>}</>}
  {tab==="Benchmarks"&&<><h2>Measured performance</h2>{item.benchmark?<><div className="lib-facts"><div><small>p50 tick latency</small><strong>{item.benchmark.p50.toFixed(3)} ms</strong></div><div><small>p95 tick latency</small><strong>{item.benchmark.p95.toFixed(3)} ms</strong></div><div><small>Samples</small><strong>{item.benchmark.samples}</strong></div></div><p className="lib-note">{item.benchmark.note}</p></>:<div className="lib-empty"><Icon name="clock" size={30}/><h3>No benchmark report yet</h3><p>Latency, memory, and task-success measurements have not been published for this release.</p></div>}<h3>Evidence still needed</h3><ul className="lib-checklist"><li>Named scenario pack and target hardware</li><li>RAM usage and maximum stable update rate</li><li>Task success and false activation rate</li></ul></>}
  {tab==="Verification"&&<><h2>Evidence, layer by layer</h2><p className="lib-muted">Availability is shown explicitly. No umbrella “verified” badge.</p>{[["Artifact identity","Computed","SHA-256 digests are computed from the current file bytes."],["Publisher identity","Not verified",item.origin==="local"?"Local namespace is self-declared; no account or signature is attached.":"Bundled collection attribution; no publisher signature is attached."],["Local tests",item.testsRun?"Smoke-tested":item.testCount?"Vectors included":"Not included",item.testsRun?"Inputs executed locally without expected-output assertions. See test-report.json.":"Included vectors have not been executed by this Library request."],["Independent replay","Not attached","No release-bound independent replay attestation is attached."],["External validation","Not attached","No external validator attestation."],["Public anchor","Not attached","No transaction or inclusion proof."]].map(([title,status,detail])=><div className="lib-evidence-row" key={title}><Icon name={status==="Computed"||status==="Smoke-tested"?"check":"clock"} size={18}/><div><h3>{title}</h3><p>{detail}</p></div><span className="lib-tag">{status}</span></div>)}</>}
  {tab==="Versions"&&<><div className="lib-section-head"><h2>Releases</h2>{item.origin==="local"&&<Link className="lib-button" href={publishHref+"&release=1"}>New version</Link>}</div><p className="lib-muted">Each release has its own immutable file digest. Existing local versions cannot be overwritten.</p>{item.releases.map(r=><Link className={"lib-release "+(r.version===item.version?"selected":"")} href={repoHref(item,r.version)+"&tab=versions"} key={r.version}><Icon name="clock"/><div><h3>v{r.version} {r.version===item.version&&<span className="lib-tag">Viewing</span>}</h3><p>{releaseDate(r.publishedAt)}</p><code>{r.digest}</code></div><Icon name="arrow" size={16}/></Link>)}{item.parent&&<p>Fork parent: <Link href={"/explore/"+item.parent.id+"?version="+item.parent.version}>{item.parent.id}@{item.parent.version}</Link></p>}</>}
  </section><aside className="lib-repo-sidebar"><section><div className="lib-eyebrow">RELEASE</div><h3>v{item.version}</h3><p>{releaseDate(item.publishedAt)}</p><label>Browse version<select value={item.version} onChange={e=>window.location.assign(repoHref(item,e.target.value))}>{item.releases.map(r=><option key={r.version} value={r.version}>v{r.version}</option>)}</select></label><hr/><small>Published by</small><Link className="lib-owner" href={"/explore?kind="+item.kind+"&q="+encodeURIComponent(item.owner)}><span>{item.owner.slice(0,2).toUpperCase()}</span>{item.owner}</Link><p className="lib-note">{item.origin==="local"?"Local namespace · self-declared":"Bundled collection · no publisher signature"}</p></section><section><h3>Package identity</h3><code className="lib-digest">{item.digest}</code><button className="lib-button" onClick={copy}>{copied?"Copied":"Copy digest"}</button><p className="lib-note">Digest of the sorted file inventory and each file’s SHA-256. Model identity is separate.</p>{item.modelDigest&&<><small>Model / Stack identity</small><code className="lib-digest">{item.modelDigest}</code></>}</section><section><h3>Use this release</h3><button className="lib-button" onClick={()=>chooseTab("Files")}><Icon name="file" size={16}/> Browse downloads</button>{item.kind==="NeuroStack"&&<Link className="lib-button" href="/compose">Open Workbench</Link>}<p className="lib-note">{item.kind==="NeuroStack"?"Source package; composed execution is not available yet.":item.kind==="NeuroBlock"?"Inspect the runtime ABI before wiring this Block into a system.":"Reference metadata only. Scientific source data is not hosted here."}</p></section></aside></div>
 </div>;
}
